### ISSUE TITLE
Name of picto is half hidden

### ISSUE THREAD

**Issue by kuhlkrein** [InteraactionGroup/AugCom#260]
On small buttons when trying to print it seems that some names of images are cut in the middle (only upper part is visible) ![F2096268-FACF-4961-A27B-E97BF83E7E26](https://user-images.githubusercontent.com/24478346/135092239-23d8f65c-884f-4977-930b-f07137a21b64.png)

**Comment by PillouMatou** [comment]
I can't reproduce this issue

**Comment by PillouMatou** [comment]
it was fix in a PR
